# Generated by Django 5.2.6 on 2025-09-13 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('current_price', models.FloatField(null=True)),
                ('market_cap', models.FloatField(null=True)),
                ('total_volume', models.FloatField(null=True)),
                ('price_change_percentage_24h', models.FloatField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cryptodashboard.coin')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('coin', 'timestamp')},
            },
        ),
    ]
